# Generated by Django 4.2.7 on 2023-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
