# Generated by Django 4.2.7 on 2023-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0002_alter_userlog_email_alter_userlog_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
